# 필요 라이브러리 임포트

In [10]:
import numpy as np

#넘파이
자료형이 하나(ndarray)  
np.array()를 이용. () 안이 전부다 리스트로 이루어짐  
행렬 계산에 많이 쓴다

In [11]:
# 변수 출력했을 때 array([])로 뜨면 무조건 넘파이
data = np.array([1,2,3,4,5])
data

array([1, 2, 3, 4, 5])

In [12]:
# 차원 확인법
data.ndim

1

In [13]:
# shape 확인
data.shape

(5,)

In [14]:
# 0, 1, 2, 3 차원과 shape 확인
d0 = np.array(1)
d1 = np.array([1,2,3])
d2 = np.array([[1,2,3],[4,5,6]])
d3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(d0.ndim, d0.shape)
print(d1.ndim, d1.shape)
print(d2.ndim, d2.shape)
print(d3.ndim, d3.shape)

0 ()
1 (3,)
2 (2, 3)
3 (2, 2, 3)


In [15]:
# 데이터 타입 확인
data.dtype

dtype('int32')

In [16]:
# 데이터 타입을 바꿔야 할 때. 원본에 바로 적용되지 않음
data.astype('float')

array([1., 2., 3., 4., 5.])

In [17]:
# 이렇게 해야 적용 된다
data = data.astype('float')
data

array([1., 2., 3., 4., 5.])

In [18]:
# 데이터 개수 확인
data.size

5

In [19]:
data = np.array([[1,2],[3,4]])

In [20]:
# 행과 열을 바꿔라
data.T

array([[1, 3],
       [2, 4]])

In [21]:
# 리스트 만들어주는 np.arange(start, stop, step)
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# 안이 0으로 채워진. 튜플로 행렬 만들어
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.zeros(2)

array([0., 0.])

In [25]:
# 안이 1으로 채워진. 튜플로 행렬 만들어
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
# 지정 값으로 채워진. 튜플로 행렬 만들어
np.full((2,3,4), fill_value=5)

array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])

In [27]:
# 단위 행렬
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [29]:
# 0~1 사이 균일분포
np.random.rand(2,3)
# 평균 0, 표준편차 1을 따르는
np.random.randn(2,3)
# 범위 내의 정수
np.random.randint(10, size=(3,5))
np.random.randint(5, 15, size=(3, 5)) # 5~14 사이의 정수

array([[ 7, 10, 13, 10, 10],
       [13,  9,  8,  7,  8],
       [ 6, 14, 10,  8, 13]])

In [30]:
data = np.arange(1,10)
data.size

9

In [31]:
# 데이터 shape을 바꿔야 할 때. 원본에 바로 적용되지 않음
data.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 행렬의 연산

In [32]:
# 리스트의 +는 연결
l_data1 = [1,2,3]
l_data2 = [4,5,6]
print(l_data1 + l_data2)

# 넘파이의 +는 행렬 덧셈
n_data1 = np.array([1,2,3])
n_data2 = np.array([4,5,6])
print(n_data1 + n_data2)

[1, 2, 3, 4, 5, 6]
[5 7 9]


# 통계 관련 함수

In [33]:
data = np.array([[1,2,3],[10,20,30]])
data

array([[ 1,  2,  3],
       [10, 20, 30]])

In [34]:
# 합
data.sum()

66

axis
- 0이면 열 기준으로 무언가를 함
- 1이면 행 기준으로 무언가를 함

In [35]:
# 열 기준의 합
data.sum(axis=0)

array([11, 22, 33])

In [36]:
# 행 기준의 합
data.sum(axis=1)

array([ 6, 60])

In [37]:
# 평균
data.mean()

11.0

In [38]:
# 열 기준의 평균
data.mean(axis=0)

array([ 5.5, 11. , 16.5])

In [39]:
# 분산 클 수록 평균으로부터 퍼져있다
data.var()

114.66666666666667

In [40]:
# 표준편차. 분산의 제곱근
data.std()

10.708252269472673

In [41]:
# 최대값
data.max()

30

In [42]:
# 최소값
data.min()

1

# 주, 월 별 매출 기록인 data_week 파일로 실습

In [43]:
data = ['40,52,11,95,52,61,21\n',
 '53,17,83,34,29,95,51\n',
 '3,2,3,35,62,8,42\n',
 '30,10,8,5,39,49,82\n']

In [44]:
# 데이터 개수 파악
len(data)

4

In [45]:
# 데이터 내용 확인
data[0]

'40,52,11,95,52,61,21\n'

In [46]:
# 줄바꿈 제거: replace, strip
data[0].strip()

'40,52,11,95,52,61,21'

In [47]:
# ,를 기준으로 쪼개기
data[0].strip().split(',')

['40', '52', '11', '95', '52', '61', '21']

In [48]:
list(map(int, data[0].strip().split(',')))

[40, 52, 11, 95, 52, 61, 21]

In [49]:
data

['40,52,11,95,52,61,21\n',
 '53,17,83,34,29,95,51\n',
 '3,2,3,35,62,8,42\n',
 '30,10,8,5,39,49,82\n']

In [50]:
# 이차 형태의 리스트로 만들기
new_data = [d.strip().split(',') for d in data]
new_data

[['40', '52', '11', '95', '52', '61', '21'],
 ['53', '17', '83', '34', '29', '95', '51'],
 ['3', '2', '3', '35', '62', '8', '42'],
 ['30', '10', '8', '5', '39', '49', '82']]

In [51]:
# 넘파이에 집어넣으면서 형 변환
result = np.array(new_data, dtype='int')

In [52]:
# 넘파이에서 형 변환
np.array(new_data).astype('int')

array([[40, 52, 11, 95, 52, 61, 21],
       [53, 17, 83, 34, 29, 95, 51],
       [ 3,  2,  3, 35, 62,  8, 42],
       [30, 10,  8,  5, 39, 49, 82]])

In [53]:
# 가장 많이 번 날
result.max()

95

In [54]:
# flatten 후 인덱스 번호를 리턴
result.argmin()

15

In [55]:
# 원래 shape의 인덱스 번호를 알고 싶으면
min_idx = result.argmin()

np.unravel_index(min_idx, result.shape) # 셋째 주 화요일이 매출이 가장 적음

(2, 1)

In [56]:
# 주 별로 많이 번 날
# 셋 째 주가 제일 적으니 마케팅을 하자
result.sum(axis=1)

array([332, 362, 155, 223])

In [57]:
# 요일 별 합계
result.sum(axis=0)

array([126,  81, 105, 169, 182, 213, 196])

In [58]:
# 요일 별 평균
# 화, 수가 적으니 마케팅을 하자
result.mean(axis=0)

array([31.5 , 20.25, 26.25, 42.25, 45.5 , 53.25, 49.  ])